env:
  browser: true
  es6: true
  node: true
extends:
  - airbnb
rules:
  quotes: [1, "double", { "avoidEscape": true }]
  comma-dangle: [2, "always-multiline"]
  react/jsx-filename-extension: 0
  react/react-in-jsx-scope: 0
  react/jsx-one-expression-per-line: 0
  import/no-mutable-exports: 0
  no-param-reassign: [2, { "props": false }]
  no-plusplus: 0
  no-underscore-dangle: off
  class-methods-use-this: 0
  no-unused-vars: 0
  operator-linebreak: 0
  no-restricted-syntax: 0
  consistent-return: 0
  no-shadow: 0
  guard-for-in: 0
  max-len: 0
